### ISSUE TITLE
Resources Min / Max and All resources button

### ISSUE THREAD

**Issue by xteriumboy** [Thisishowwedoit-2Moons/2moons-xterium#1]
game.php?page=fleetStep2 when need to select the resources Min / Max and All resources button not work

**Comment by xteriumboy** [comment]
Loading failed for the <script> with source “https://static.final-space.com/media/gamemedia/scripts/game/qtip.js?4.0.13”. game.php:75:1
Loading failed for the <script> with source “https://static.final-space.com/media/gamemedia/scripts/game/topnav.js?4.0.13”. game.php:76:1
ReferenceError: resourceTicker is not defined[Learn More] game.php:387:4
ReferenceError: pointsPrice is not defined[Learn More] flotten.js:532:3
unreachable code after return statement[Learn More] js:87:1789
unreachable code after return statement[Learn More] js:147:462
unreachable code after return statement[Learn More] js:147:506
unreachable code after return statement[Learn More] js:147:462
unreachable code after return statement[Learn More] js:87:1789
unreachable code after return statement[Learn More] js:147:506

**Comment by Darkside2016** [comment]
ReferenceError: getRessource is not defined flotten.js:155:6 

	maxResource
https://static.warofgalaxyz.eu/media/gamemedia/scripts/game/flotten.js:155:6
onclick
https://play.warofgalaxyz.eu/game.php:1:1

**Comment by Thisishowwedoit-2Moons** [comment]
well its obvious the links are bad ? fix links and problem will be resolved
https://github.com/Thisishowwedoit-2Moons/2moons-xterium/blob/master/GAME_FILES/TYPE_GAME_ONE/styles/templates/game/main.header.tpl#L93

**Comment by Thisishowwedoit-2Moons** [comment]
you are missing files

https://static.warofgalaxyz.eu/media/gamemedia/scripts/game/topnav.js upload it and will be fixed

**Comment by xteriumboy** [comment]
After uploaded this file i see another bug ,now if i press for cristall/metal/deuterium  the max is ok,but if i press again for another resources is inserted but not calculated the remaining space 
Capacity available: -2.287.839.601
[https://imgur.com/a/6Tku2og](url)
