### ISSUE TITLE
Cronjob Stats History

### ISSUE THREAD

**Issue by xteriumboy** [Thisishowwedoit-2Moons/2moons-xterium#2]
PHP Fatal error: Cannot redeclare class statbuilder in /home/GAME_FILES/TYPE_GAME_ONE/includes/classes/class.statbuilder.php on line 29

line 29 = class statbuilder

Cronjob Stats History make this problem

**Comment by Thisishowwedoit-2Moons** [comment]
what have you set as cronjob timer for stat and stat history cron ?
