### ISSUE TITLE
Auctioneer 

### ISSUE THREAD

**Issue by xteriumboy** [Thisishowwedoit-2Moons/2moons-xterium#3]
After Auctioneer  end if you win something ,the system add 3 item not 1

**Comment by xteriumboy** [comment]
i changed in config but cant find in admin panel 
thanks

**Comment by Thisishowwedoit-2Moons** [comment]
well its possible you cant change in admin panel, i dont have the game installed anymore so i cant verify but yu can change it via phpmyadmin.

I always worked with phpmyadmin, its rare if i worked with the admin panel, i will try to reinstall game this weekend if i find the time to check
