### ISSUE TITLE
Universe reset Page

### ISSUE THREAD

**Issue by Darkside2016** [Thisishowwedoit-2Moons/2moons-xterium#6]
the universe reset page in admin menu does not work
only white page

**Comment by Darkside2016** [comment]
both ......
after i have changed this line 
 if ($USER['id'] != ROOT_USER || $_GET['sid'] != session_id()) exit;
into
if ($USER['id'] != ROOT_USER) exit;

it is working .......

but after the reset i run in error with the statbuilder

**Comment by Thisishowwedoit-2Moons** [comment]
helo,

the sid is only the session id you are on actually, not really important as first check is enough to show or block  the page.  i will create an admin abstract page where the $sid will be defined and extend the php files of the admin panel with it.

this will be done this weekend, what is the statbuilder problem ?

**Comment by Darkside2016** [comment]
this error appears after the uni reset page

[12-Dec-2018 17:50:01] USER ERROR: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1"
File: /var/www/virtual/warofgalaxyz.eu/wog3/htdocs/includes/classes/Database.class.php | Line: 242
URL: https://wog3.warofgalaxyz.eu/cronPanel.php?cronjobID=111 | Version: 2.03.git
USERID: 
Stack trace:
#0 /includes/classes/Database.class.php(242): PDO-&gt;query('INSERT INTO uni...')
#1 /includes/classes/class.statbuilder.php(169): Database-&gt;nativeQuery('INSERT INTO uni...')
#2 /includes/classes/class.statbuilder.php(507): statbuilder-&gt;SaveDataIntoDB('INSERT INTO %%S...')
#3 /includes/classes/cronjob/StatisticCronjob.class.php(40): statbuilder-&gt;MakeStats()
#4 /includes/classes/Cronjob.class.php(68): StatisticCronjob-&gt;run()
#5 /cronPanel.php(29): Cronjob::execute('2')
#6 {main}


wog3 is a test ...... i can do some modification and testing all other

**Comment by Thisishowwedoit-2Moons** [comment]
did you deleted the beginners alliance with id 1 ?

**Comment by Darkside2016** [comment]
yep .... that was the problem,
after creating the beginners ally the stat is working

so how can the reset work without deleting the beginners ally ?

**Comment by Darkside2016** [comment]
in reset page is it possible to insert a structure for creating a root player, planet and beginner ally ?
like register page

**Comment by Thisishowwedoit-2Moons** [comment]
for sure you simply have to change the reset page, let me a moment and il update it.

**Comment by Thisishowwedoit-2Moons** [comment]
With these files, 
https://github.com/Thisishowwedoit-2Moons/2moons-xterium/commit/784db2180c646a7d499f6cdea60d3de06995593e

id 1 wont be deleted in alliance and users, its untested as i still dont have the game installed, will do that this weekend, so can you test it and keep me informed so i can close it

**Comment by Darkside2016** [comment]
line 144 - 145 must be change

`		if ($_POST['alliances']	==	'on')
			$GLOBALS['DATABASE']->multi_query("DELETE FROM ".ALLIANCE." WHERE `ally_universe` = '".Universe::getEmulated()."' AND id != 1;UPDATE ".USERS." SET `ally_id` = '0', `ally_register_time` = '0', `ally_rank_id` = '0' WHERE `universe` = ".Universe::getEmulated()." AND ally_id != 1;");
`

the first ally_id after .Universe::getEmulated()."' AND does not exist ... it must be .Universe::getEmulated()."' AND id !=1;

with this cahnges the reset is working

**Comment by Thisishowwedoit-2Moons** [comment]
indeed my bad, git is updated
