### ISSUE TITLE
Resources Min / Max and All resources button another bug

### ISSUE THREAD

**Issue by xteriumboy** [Thisishowwedoit-2Moons/2moons-xterium#7]
After uploaded this file i see another bug ,now if i press for cristall/metal/deuterium  the max is ok,but if i press again for another resources is inserted but not calculated the remaining space 
Capacity available: -2.287.839.601
[https://imgur.com/a/6Tku2og](url)

**Comment by Darkside2016** [comment]
that is wayne ...... if you hit next you will get the message that you have not enough cargo room

**Comment by Thisishowwedoit-2Moons** [comment]
consumption of deut ? i will check as i didnt had it when i was running my game
